package op

const (
	Or           = "$or"
	And          = "$and"
	Nor          = "$nor"
	Not          = "$not"
	Expr         = "$exp"
	Where        = "$where"
	In           = "$in"
	NotIn        = "$nin"
	Gt           = "$gt"
	Gte          = "$gte"
	Lt           = "$lt"
	Lte          = "$lte"
	Eq           = "$eq"
	Ne           = "$ne"
	Regex        = "$regex"
	Match        = "$match"
	Sum          = "$sum"
	Avg          = "$avg"
	StdDevPop    = "$stdDevPop"
	StdDevSamp   = "$stdDevSamp"
	First        = "$first"
	Last         = "$last"
	Push         = "$push"
	AddToSet     = "$addToSet"
	MergeObjects = "$mergeObject"
	Set          = "$set"
	Unset        = "$unset"
	Inc          = "$inc"
	SetOnInsert  = "$setOnInsert"
	Multiply     = "$multiply"
)
