package cond

const (
	OPOr           = "$or"
	OPAnd          = "$and"
	OPNor          = "$nor"
	OPNot          = "$not"
	OPExpr         = "$exp"
	OPWhere        = "$where"
	OPIn           = "$in"
	OPNotIn        = "$nin"
	OPGt           = "$gt"
	OPGte          = "$gte"
	OPLt           = "$lt"
	OPLte          = "$lte"
	OPEq           = "$eq"
	OPNe           = "$ne"
	OPRegex        = "$regex"
	OPMatch        = "$match"
	OPSum          = "$sum"
	OPAvg          = "$avg"
	OPStdDevPop    = "$stdDevPop"
	OPStdDevSamp   = "$stdDevSamp"
	OPFirst        = "$first"
	OPLast         = "$last"
	OPPush         = "$push"
	OPAddToSet     = "$addToSet"
	OPMergeObjects = "$mergeObject"
	OPSet          = "$set"
	OPUnset        = "$unset"
	OPInc          = "$inc"
	OPSetOnInsert  = "$setOnInsert"
	OPMultiply     = "$multiply"
)
